const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{Mosaico2: 0},
	{Sprite: 0},
	{janela: 0},
	{Sólido: 0},
	{suporte: 0},
	{bau: 0},
	{caixa: 0},
	{porta: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{jogador: 0},
	{sensor: 0},
	{Teclado: 0},
	{direcao: 0},
	{Piscar: 0},
	{porco_patrulheiro: 0},
	{sensor_patrulheiro_direito: 0},
	{sensor_patrulheiro_esquerda: 0},
	{porco_canhao: 0},
	{canhao: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Girar: 0},
	{bala: 0},
	{sensor_canhao: 0},
	{vida_hud: 0},
	{Sprite2: 0},
	{itens_hud: 0},
	{black_fundo: 0},
	{fala_jogador: 0},
	{FonteDeSprites: 0},
	{chave: 0},
	{Vidas: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	janela: class extends self.ISpriteInstance {},
	suporte: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	sensor: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	porco_patrulheiro: class extends self.ISpriteInstance {},
	sensor_patrulheiro_direito: class extends self.ISpriteInstance {},
	sensor_patrulheiro_esquerda: class extends self.ISpriteInstance {},
	porco_canhao: class extends self.ISpriteInstance {},
	canhao: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	sensor_canhao: class extends self.ISpriteInstance {},
	vida_hud: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	itens_hud: class extends self.ISpriteInstance {},
	black_fundo: class extends self.ISpriteInstance {},
	fala_jogador: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	chave: class extends self.ISpriteInstance {}
}